name: Generate Javadoc

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build project
        run: mvn clean package
      - name: Generate Javadoc
        run: mvn javadoc:jar
      - name: Upload Javadoc to GitHub Pages
        uses: actions/upload-artifact@v3
        with:
          name: javadoc
          path: target/site/apidocs
