name: Maven Package

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout main
      uses: actions/checkout@v4
      with:
        path: main
    - name: Checkout rxue.github.io
      uses: actions/checkout@v4
      with:
        repository: rxue/rxue.github.io
        path: rxue.github.io
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Package dictionary-jpa and then add Javadoc to gh-pages branch
      run: |
       cd main
       mvn clean package
       cd ../rxue.github.io
       mkdir dictionary-jpa
       cp ../main/target/apidocs dictionary-jpa/
       git config user.name "Rui Xue Bot"
       git config user.email "ruixue.fi@gmail.com"
       git add dictionary-jpa/apidocs/*

