name: Maven Package

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Package dictionary-jpa and then add Javadoc to gh-pages branch
      run: |
       git config user.name "Rui Xue Bot"
       git config user.email "ruixue.fi@gmail.com"
       if [[ ! `git branch |grep gh-pages` ]]; then git checkout --orphan gh-pages; fi
       mvn --file pom.xml -B clean package
       git rm -rf src
       git rm -f pom.xml
       git rm -f README.md
       mv target/apidocs .
       git add apidocs/*
       echo "directory state after checkout apidocs"
       git commit -m "add apidoc to gh-pages"
       git push origin gh-pages
      

