name: Maven Package

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build dictionary-jpa and execute integration tests with Maven
      run: mvn --file pom.xml -B clean package
    - name: add Javadoc to gh-pages branch
      run: |
       cp -r target/apidocs .
       git config --global user.email "ruixue.fi@gmail.com"
       git config --global user.name "Rui Xue"
       if [[ ! `git branch |grep gh-pages` ]]; then git checkout --orphan gh-pages; fi
       git branch
       git checkout main -- apidoc .
       git commit -m "add apidoc to gh-pages"
       git push origin gh-pages
      

