name: Maven Package

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout rxue.github.io
      uses: actions/checkout@v4
      with:
        repository: rxue/rxue.github.io
        ref: gh-pages
        path: rxue.github.io
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: check host file system structure
      run: |
        pwd
        ls -alR /home
        cd rxue.github.io
        git config user.name "Rui Xue - Bot"
        git config user.email "ruixue.fi@gmail.com"
        echo "test" > test.txt
        git add test.txt
        git commit -m "add file to rxue.github.io repo in current repo - dictionary-jpa"
        git push origin gh-pages
