name: Maven Package

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Checkout current main branch
      uses: actions/checkout@v4
      with:
          path: main
    - name: Checkout gh-pages branch
      uses: actions/checkout@v4
      with:
          path: gh-pages
          ref: gh-pages
    - name: Generate Java Doc and then copy it to gh-pages branch
      run: |
        cd main
        mvn clean package -DskipTests
        cd ../gh-pages
        cp -r ../main/target/apidocs .
        git config user.name "Rui Xue - Bot"
        git config user.email "ruixue.fi@gmail.com"
        echo "DEBUG::going to commit apidocs files"
        git commit -m "add aipidoc to gh-pages branch so that it can be browsed through browser"
        echo "DEBUG::going to push change to gh-pages branch"
        git push origin gh-pages
